name: MA3 Plugin Build

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    name: MA3 Plugin Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Release File
        uses: bootsie123/ma3-plugin-action@v1.0.1
        with:
          plugins: >-
            [
              {
                "name": "Auto Groups",
                "version": "1.0.0",
                "path": "auto-groups.lua"
              }
            ]
          outputFile: ./auto-groups.xml

      - name: Push Changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Automated: update MA3 plugin release file"
          git push
